// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PasswordsMenadger.Models
{
    public partial class Site
    {
        public Site()
        {
            Users = new HashSet<User>();
        }

        public int Id { get; set; }
        public string UrlPath { get; set; }
        public string Title { get; set; }

        public virtual ICollection<User> Users { get; set; }
    }
}